#!/usr/bin/env python3

import os
import argparse


def do_main():
    # get current directory of _this_ file.
    current_dir = os.path.dirname(os.path.realpath(__file__))
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug",
                        help="Verbose debug log",
                        action='store_true')
    parser.add_argument("--debugger",
                        help="launch QTE with gdb",
                        action='store_true')
    parser.add_argument("--debug_engine",
                        help="Which debugging engine to use (default gdb)",
                        choices=['rr', 'gdb'],
                        default='gdb')
    parser.add_argument("--strace",
                        help="Allow passing of the strace flag to QEMU",
                        action='store_true')
    parser.add_argument("target",
                        help="Target program and arguments",
                        nargs=argparse.REMAINDER)
    parser.add_argument(
        "--tcg-ir",
        help=
        "Print out TCG IR opcode, input ASM and output ASM (NOTE: VERY VERBOSE)",
        action='store_true')

    args = parser.parse_args()

    # Copy
    env = os.environ.copy()
    if (args.debug):
        env['QTE_DEBUG'] = '1'

    # LD_PRELOAD our interception library into the target program and run it
    # through our modified qemu-user
    argv = [
        os.path.join(current_dir, "qte-qemu"),
        "-E",
        "LD_PRELOAD={}".format(os.path.join(current_dir, "libqte.so")),
    ]
    if ((args.strace)):
        argv.append('-strace')
    if ((args.debugger) and (args.debug_engine == 'gdb')):
        argv.insert(0, '/usr/bin/gdb')
        argv.insert(1, '--args')
    if ((args.debugger) and (args.debug_engine == 'rr')):
        argv.insert(0, '/usr/bin/rr')
        argv.insert(1, 'record')
    if (args.tcg_ir):
        argv.append("-d")
        argv.append("in_asm,op,out_asm")

    argv += args.target
    print("{}".format(argv))
    # Now execute the target program.
    os.execve(argv[0], argv, env)


if __name__ == '__main__':
    do_main()
